name: Build and Publish TableKit for jsDelivr

on:
  push:
    tags:
      - 'v*.*.*'       # trigger on version tags like v1.0.0
  workflow_dispatch:    # manual trigger option

permissions:
  contents: write       # required to commit/push and create tags

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repo
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # need full history for tags

      # 2. Setup Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      # 3. Install dependencies
      - run: npm ci

      # 4. Build the library
      - run: npm run build

      # 5. Verify build output
      - run: ls -la dist

      # 6. Configure git for pushing back
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # 7. Create or switch to the build branch
      - run: |
          git checkout -B dist-build

      # 8. Copy dist files into branch
      - run: |
          rm -rf *           # clean branch
          cp -r dist/* .     # copy from current repo root
      
      # 9. Commit the built files
      - run: |
          git add .
          git commit -m "Build dist for $GITHUB_REF_NAME" || echo "No changes to commit"

      # 10. Push branch
      - run: git push origin dist-build --force

      # 11. Update release tag for this build
      - run: |
          git tag -f $GITHUB_REF_NAME
          git push origin $GITHUB_REF_NAME --force

      # 12. Update 'latest' tag
      - run: |
          git tag -f latest
          git push origin latest --force
