name: Build and Publish TableKit for jsDelivr

on:
  push:
    tags:
      - 'v*.*.*'       # trigger on version tags like v1.0.0
  workflow_dispatch:    # allow manual trigger

permissions:
  contents: write       # required for pushing branch and tags

jobs:
  build-and-publish:
    runs-on: ubuntu-latest
    steps:
      # 1. Checkout repo
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0  # fetch all history for tags

      # 2. Setup Node.js
      - uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      # 3. Install dependencies
      - run: npm ci

      # 4. Build the library
      - run: npm run build

      # 5. Verify build output
      - run: ls -la dist

      # 6. Configure git
      - run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

      # 7. Create a worktree for dist-build branch
      - run: git worktree add build dist-build || git worktree add -B dist-build build origin/dist-build

      # 8. Copy dist/ files into worktree
      - run: cp -r dist/* build/

      # 9. Commit and push changes
      - run: |
          cd build
          git add .
          git commit -m "Build dist for $GITHUB_REF_NAME" || echo "No changes to commit"
          git push origin dist-build --force

      # 10. Update the release tag (version tag)
      - run: |
          git tag -f $GITHUB_REF_NAME
          git push origin $GITHUB_REF_NAME --force

      # 11. Update 'latest' tag
      - run: |
          git tag -f latest
          git push origin latest --force
