name: Build and Release TableKit

on:
  push:
    tags:
      - 'v*.*.*'   # trigger only on version tags like v1.0.0
  workflow_dispatch:

jobs:
  build-and-release:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the repo
      - name: Checkout repo
        uses: actions/checkout@v3

      # 2️⃣ Setup Node
      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '20'
          cache: 'npm'

      # 3️⃣ Install dependencies
      - name: Install dependencies
        run: npm ci

      # 4️⃣ Build the library
      - name: Build library
        run: npm run build

      # 5️⃣ Create GitHub release and upload dist
      - name: Create Release
        uses: ncipollo/release-action@v1.10.0
        with:
          tag: ${{ github.ref_name }}
          name: Release ${{ github.ref_name }}
          files: |
            dist/**
